# Generated by Django 5.2.8 on 2025-11-13 04:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('musica', 'Música'), ('deporte', 'Deporte'), ('cultural', 'Cultural'), ('gastronomia', 'Gastronomía'), ('educativo', 'Educativo'), ('religioso', 'Religioso'), ('feria', 'Feria'), ('teatro', 'Teatro'), ('danza', 'Danza'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin (opcional)')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección completa (opcional)')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0.00 para eventos gratuitos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen del evento')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto (teléfono, email, etc.)')),
                ('enlace', models.URLField(blank=True, verbose_name='Enlace adicional (opcional)')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar el evento', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
                'indexes': [models.Index(fields=['fecha_inicio'], name='chatbot_eve_fecha_i_8bd07d_idx'), models.Index(fields=['categoria'], name='chatbot_eve_categor_81f9a2_idx'), models.Index(fields=['activo'], name='chatbot_eve_activo_6a28e1_idx')],
            },
        ),
    ]
