"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@487*1a93p$mx^@dq)^n=9elzcpg*bz835%p)y9260^e488a(9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatbot',  # App principal del chatbot
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Gemini API
GEMINI_API_KEY = 'AIzaSyBrbwPfE0of5FeKPuRWV7n8OBa1SYoq5xE'

# Django Unfold Configuration
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "CantaClaro - Admin",
    "SITE_HEADER": "CantaClaro",
    "SITE_SUBHEADER": "Gestión de Eventos en Loja",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "16px",
    "SITE_SYMBOL": "celebration",  # Ícono de celebración/evento
    
    # Colores personalizados basados en el chatbot
    # Gradiente principal: #667eea (azul morado) a #764ba2 (morado)
    "COLORS": {
        "base": {
            # Base oscura inspirada en el fondo del chatbot
            "50": "oklch(98% 0.002 260)",
            "100": "oklch(95% 0.005 260)",
            "200": "oklch(90% 0.008 260)",
            "300": "oklch(82% 0.012 260)",
            "400": "oklch(70% 0.018 260)",
            "500": "oklch(55% 0.025 260)",
            "600": "oklch(45% 0.030 260)",
            "700": "oklch(35% 0.035 260)",
            "800": "oklch(25% 0.032 260)",
            "900": "oklch(18% 0.028 260)",
            "950": "oklch(12% 0.025 260)",
        },
        "primary": {
            # Gradiente principal del chatbot convertido a oklch
            # #667eea = rgb(102, 126, 234) ≈ oklch(65% 0.14 280)
            # #764ba2 = rgb(118, 75, 162) ≈ oklch(50% 0.14 310)
            "50": "oklch(97% 0.025 285)",
            "100": "oklch(94% 0.045 285)",
            "200": "oklch(90% 0.065 285)",
            "300": "oklch(85% 0.085 285)",
            "400": "oklch(75% 0.115 290)",
            "500": "oklch(68% 0.135 295)",  # Intermedio entre los dos
            "600": "oklch(65% 0.140 295)",  # #667eea principal
            "700": "oklch(58% 0.140 305)",  # #764ba2
            "800": "oklch(50% 0.135 310)",
            "900": "oklch(43% 0.125 315)",
            "950": "oklch(35% 0.110 320)",
        },
        "font": {
            "subtle-light": "oklch(60% 0.010 260)",
            "subtle-dark": "oklch(70% 0.010 260)",
            "default-light": "oklch(45% 0.015 260)",
            "default-dark": "oklch(80% 0.010 260)",
            "important-light": "oklch(25% 0.020 260)",
            "important-dark": "oklch(95% 0.005 260)",
        },
    },
}
