"""
Comando de Django para poblar la base de datos con eventos de prueba.
Uso: python manage.py poblar_eventos
"""
from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import datetime, timedelta
from chatbot.models import Evento
from decimal import Decimal


class Command(BaseCommand):
    help = 'Pobla la base de datos con eventos de prueba para la ciudad de Loja'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Creando eventos de prueba...'))
        
        hoy = timezone.now()
        
        eventos_data = [
            # Eventos de hoy
            {
                'titulo': 'Festival de Música Andina',
                'descripcion': 'Gran festival de música andina con artistas locales e internacionales. Ven a disfrutar de los mejores sonidos de los Andes.',
                'categoria': 'musica',
                'fecha_inicio': hoy.replace(hour=18, minute=0, second=0, microsecond=0),
                'fecha_fin': hoy.replace(hour=23, minute=0, second=0, microsecond=0),
                'ubicacion': 'Parque Central de Loja',
                'direccion': 'Parque Central, Centro Histórico, Loja',
                'precio': Decimal('15.00'),
                'contacto': '0987654321',
            },
            {
                'titulo': 'Clase de Yoga Gratuita',
                'descripcion': 'Clase de yoga al aire libre para todos los niveles. Trae tu mat y disfruta de una sesión relajante.',
                'categoria': 'deporte',
                'fecha_inicio': hoy.replace(hour=7, minute=0, second=0, microsecond=0),
                'fecha_fin': hoy.replace(hour=8, minute=30, second=0, microsecond=0),
                'ubicacion': 'Parque Jipiro',
                'direccion': 'Parque Jipiro, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'yoga.loja@email.com',
            },
            
            # Eventos de mañana
            {
                'titulo': 'Feria Artesanal del Valle',
                'descripcion': 'Feria con productos artesanales, comida típica y música en vivo. Apoya a los artesanos locales.',
                'categoria': 'feria',
                'fecha_inicio': (hoy + timedelta(days=1)).replace(hour=9, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=1)).replace(hour=20, minute=0, second=0, microsecond=0),
                'ubicacion': 'Plaza de San Sebastián',
                'direccion': 'Plaza de San Sebastián, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'feria.artesanal@loja.gob.ec',
            },
            {
                'titulo': 'Concierto de Rock Nacional',
                'descripcion': 'Los mejores grupos de rock nacional se presentan en Loja. No te pierdas esta noche llena de energía.',
                'categoria': 'musica',
                'fecha_inicio': (hoy + timedelta(days=1)).replace(hour=20, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=1)).replace(hour=23, minute=30, second=0, microsecond=0),
                'ubicacion': 'Coliseo Ciudad de Loja',
                'direccion': 'Av. Universitaria, Loja',
                'precio': Decimal('25.00'),
                'contacto': 'ventas@coliseoloja.com',
            },
            
            # Eventos de esta semana
            {
                'titulo': 'Obra de Teatro: "El Quijote"',
                'descripcion': 'Adaptación moderna de la obra clásica de Cervantes. Presentación del grupo teatral local.',
                'categoria': 'teatro',
                'fecha_inicio': (hoy + timedelta(days=2)).replace(hour=19, minute=30, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=2)).replace(hour=21, minute=30, second=0, microsecond=0),
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Calle Bolívar, Centro Histórico, Loja',
                'precio': Decimal('10.00'),
                'contacto': 'teatro.bolivar@loja.gob.ec',
            },
            {
                'titulo': 'Taller de Cocina Ecuatoriana',
                'descripcion': 'Aprende a preparar los platos típicos de Loja. Incluye degustación de todos los platos preparados.',
                'categoria': 'gastronomia',
                'fecha_inicio': (hoy + timedelta(days=3)).replace(hour=15, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=3)).replace(hour=18, minute=0, second=0, microsecond=0),
                'ubicacion': 'Centro Culinario Loja',
                'direccion': 'Av. 24 de Mayo, Loja',
                'precio': Decimal('30.00'),
                'contacto': 'cocina.loja@email.com',
            },
            {
                'titulo': 'Maratón de Loja 2024',
                'descripcion': 'Maratón anual de la ciudad. Categorías: 5K, 10K y 21K. Inscripciones abiertas.',
                'categoria': 'deporte',
                'fecha_inicio': (hoy + timedelta(days=4)).replace(hour=6, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=4)).replace(hour=12, minute=0, second=0, microsecond=0),
                'ubicacion': 'Parque Lineal',
                'direccion': 'Parque Lineal, Loja',
                'precio': Decimal('20.00'),
                'contacto': 'maraton.loja@deportes.gob.ec',
            },
            
            # Eventos culturales
            {
                'titulo': 'Exposición de Arte Contemporáneo',
                'descripcion': 'Exposición de artistas locales e internacionales. Obras de pintura, escultura y fotografía.',
                'categoria': 'cultural',
                'fecha_inicio': (hoy + timedelta(days=5)).replace(hour=10, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=12)).replace(hour=18, minute=0, second=0, microsecond=0),
                'ubicacion': 'Museo de Arte de Loja',
                'direccion': 'Calle Bernardo Valdivieso, Loja',
                'precio': Decimal('5.00'),
                'contacto': 'museo.arte@loja.gob.ec',
            },
            {
                'titulo': 'Festival de Danza Folclórica',
                'descripcion': 'Grupos de danza de toda la región se reúnen para celebrar la cultura lojana.',
                'categoria': 'danza',
                'fecha_inicio': (hoy + timedelta(days=6)).replace(hour=17, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=6)).replace(hour=22, minute=0, second=0, microsecond=0),
                'ubicacion': 'Plaza de la Independencia',
                'direccion': 'Plaza de la Independencia, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'danza.loja@cultura.gob.ec',
            },
            
            # Eventos educativos
            {
                'titulo': 'Conferencia: Inteligencia Artificial',
                'descripcion': 'Conferencia sobre el futuro de la IA y su impacto en la sociedad. Incluye demostraciones prácticas.',
                'categoria': 'educativo',
                'fecha_inicio': (hoy + timedelta(days=7)).replace(hour=15, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=7)).replace(hour=17, minute=30, second=0, microsecond=0),
                'ubicacion': 'Universidad Nacional de Loja',
                'direccion': 'Campus Universitario, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'conferencias@unl.edu.ec',
            },
            
            # Eventos religiosos
            {
                'titulo': 'Procesión de la Virgen del Cisne',
                'descripcion': 'Procesión tradicional en honor a la Virgen del Cisne, patrona de Loja.',
                'categoria': 'religioso',
                'fecha_inicio': (hoy + timedelta(days=8)).replace(hour=8, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=8)).replace(hour=12, minute=0, second=0, microsecond=0),
                'ubicacion': 'Basilica de Loja',
                'direccion': 'Calle 10 de Agosto, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'basilica.loja@iglesia.ec',
            },
            
            # Más eventos variados
            {
                'titulo': 'Noche de Jazz en Loja',
                'descripcion': 'Presentación de jazz en vivo con músicos locales. Ambiente íntimo y acogedor.',
                'categoria': 'musica',
                'fecha_inicio': (hoy + timedelta(days=9)).replace(hour=20, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=9)).replace(hour=23, minute=0, second=0, microsecond=0),
                'ubicacion': 'Café Cultural Loja',
                'direccion': 'Calle Lourdes, Loja',
                'precio': Decimal('12.00'),
                'contacto': 'jazz.loja@email.com',
            },
            {
                'titulo': 'Feria de Emprendedores',
                'descripcion': 'Feria donde emprendedores locales muestran sus productos y servicios. Apoya el comercio local.',
                'categoria': 'feria',
                'fecha_inicio': (hoy + timedelta(days=10)).replace(hour=9, minute=0, second=0, microsecond=0),
                'fecha_fin': (hoy + timedelta(days=10)).replace(hour=18, minute=0, second=0, microsecond=0),
                'ubicacion': 'Centro Comercial Loja',
                'direccion': 'Av. 8 de Diciembre, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'emprendedores@loja.gob.ec',
            },
            
            # Evento específico para probar fecha exacta (3 de noviembre)
            {
                'titulo': 'Festival de la Cerveza Artesanal',
                'descripcion': 'Festival con las mejores cervezas artesanales de la región. Música en vivo y comida.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2024, 11, 3, 16, 0, 0),
                'fecha_fin': datetime(2024, 11, 3, 23, 0, 0),
                'ubicacion': 'Parque Recreacional Jipiro',
                'direccion': 'Parque Jipiro, Loja',
                'precio': Decimal('18.00'),
                'contacto': 'cerveza.artesanal@loja.com',
            },
            {
                'titulo': 'Concierto de Música Clásica',
                'descripcion': 'Orquesta sinfónica de Loja presenta un repertorio de música clásica internacional.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2024, 11, 3, 19, 30, 0),
                'fecha_fin': datetime(2024, 11, 3, 21, 30, 0),
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Calle Bolívar, Centro Histórico, Loja',
                'precio': Decimal('20.00'),
                'contacto': 'orquesta.loja@cultura.gob.ec',
            },
            
            # Eventos entre 15 y 20 de noviembre para probar rangos de fechas
            {
                'titulo': 'Festival de Cine Independiente',
                'descripcion': 'Proyección de películas independientes de directores ecuatorianos. Entrada gratuita.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2024, 11, 15, 18, 0, 0),
                'fecha_fin': datetime(2024, 11, 15, 22, 0, 0),
                'ubicacion': 'Centro Cultural Loja',
                'direccion': 'Av. 24 de Mayo, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'cine.loja@cultura.gob.ec',
            },
            {
                'titulo': 'Conferencia de Tecnología',
                'descripcion': 'Conferencia sobre las últimas tendencias en tecnología e innovación. Incluye networking.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2024, 11, 16, 14, 0, 0),
                'fecha_fin': datetime(2024, 11, 16, 18, 0, 0),
                'ubicacion': 'Universidad Técnica Particular de Loja',
                'direccion': 'Campus UTPL, Loja',
                'precio': Decimal('15.00'),
                'contacto': 'tecnologia@utpl.edu.ec',
            },
            {
                'titulo': 'Festival de Comida Típica',
                'descripcion': 'Festival gastronómico con los mejores platos típicos de Loja. Música folclórica en vivo.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2024, 11, 17, 10, 0, 0),
                'fecha_fin': datetime(2024, 11, 17, 20, 0, 0),
                'ubicacion': 'Plaza de San Francisco',
                'direccion': 'Plaza de San Francisco, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'gastronomia.loja@turismo.gob.ec',
            },
            {
                'titulo': 'Torneo de Fútbol Local',
                'descripcion': 'Final del torneo de fútbol local. Ven a apoyar a los equipos de Loja.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2024, 11, 18, 15, 0, 0),
                'fecha_fin': datetime(2024, 11, 18, 18, 0, 0),
                'ubicacion': 'Estadio Reina del Cisne',
                'direccion': 'Av. Universitaria, Loja',
                'precio': Decimal('8.00'),
                'contacto': 'deportes.loja@municipio.gob.ec',
            },
            {
                'titulo': 'Noche de Poesía',
                'descripcion': 'Lectura de poesía con poetas locales e invitados especiales. Ambiente íntimo y acogedor.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2024, 11, 19, 19, 0, 0),
                'fecha_fin': datetime(2024, 11, 19, 21, 0, 0),
                'ubicacion': 'Café Literario Loja',
                'direccion': 'Calle Lourdes, Loja',
                'precio': Decimal('5.00'),
                'contacto': 'poesia.loja@cultura.gob.ec',
            },
            {
                'titulo': 'Feria de Artesanías',
                'descripcion': 'Feria con productos artesanales de toda la provincia. Ideal para comprar regalos únicos.',
                'categoria': 'feria',
                'fecha_inicio': datetime(2024, 11, 20, 9, 0, 0),
                'fecha_fin': datetime(2024, 11, 20, 19, 0, 0),
                'ubicacion': 'Parque Central de Loja',
                'direccion': 'Parque Central, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'artesanias.loja@turismo.gob.ec',
            },
            
            # Eventos de noviembre-diciembre 2025
            {
                'titulo': 'Concierto solidario: "Un Invitado Inesperado"',
                'descripcion': 'Presentación del EP "Un Invitado Inesperado" de la cantante local María José Reipan, acompañada por la Orquesta Sinfónica Municipal de Loja dirigida por el maestro Nuery Vivas. Se trata de un concierto de fusión de géneros con carácter benéfico. La entrada es solidaria – se pide a los asistentes aportar víveres no perecederos (caramelos, galletas, etc.) para fines sociales. El espectáculo es apto para todo público y promueve la cultura local.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 11, 26, 19, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Calle Rocafuerte entre Bernardo Valdivieso y Olmedo, Centro Histórico de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'teatro.bolivar@loja.gob.ec',
                'enlace': 'https://loja.gob.ec',
            },
            {
                'titulo': 'Presentación de libro: "Ángel Felicísimo Rojas: contexto, crítica y vanguardismo en la literatura ecuatoriana"',
                'descripcion': 'Charla y presentación del libro de investigación del autor Cristhian Sarango Jaramillo sobre la obra narrativa de Ángel Felicísimo Rojas. El evento analizará el compromiso social y las problemáticas reflejadas en las novelas de Rojas, empleando enfoques teóricos (Gramsci, Althusser, Foucault, etc.) para contextualizar su aporte literario.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 11, 27, 10, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Aula Magna de la UTPL',
                'direccion': 'Universidad Técnica Particular de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'Universidad Técnica Particular de Loja',
                'enlace': 'https://eventos.utpl.edu.ec',
            },
            {
                'titulo': '5K Pasos Solidarios (carrera atlética)',
                'descripcion': 'Carrera atlética de 5 km organizada por estudiantes de Derecho y Administración de Empresas de la UTPL, en colaboración con AEMPPI UTPL. El objetivo es recaudar fondos y apoyar a la Unidad Especializada "Ciudad de Loja No. 2" beneficiando a niños y familias en situación de vulnerabilidad. Se fomenta la práctica deportiva y la solidaridad comunitaria. El evento contará con dos categorías (17–30 años y 31 años en adelante).',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 11, 29, 7, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'UTPL',
                'direccion': 'Punto de partida en la UTPL (carrera de 5 km por las calles de Loja)',
                'precio': Decimal('5.00'),
                'contacto': 'Universidad Técnica Particular de Loja',
                'enlace': 'https://eventos.utpl.edu.ec',
            },
            {
                'titulo': 'I Festival Bells & Voices UTPL (Villancicos en inglés)',
                'descripcion': 'Festival navideño de villancicos interpretados en inglés, organizado por la UTPL a través del Vicerrectorado Académico. El evento (denominado "Bells & Voices") busca enriquecer el aprendizaje de una segunda lengua mediante la música, promoviendo el espíritu festivo y la convivencia universitaria. Participarán coros y grupos locales interpretando canciones típicas de Navidad en inglés.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 11, 16, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Centro de Convenciones UTPL',
                'direccion': 'Universidad Técnica Particular de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'Prof. Patricia Piedra (pnpiedra@utpl.edu.ec)',
                'enlace': 'https://eventos.utpl.edu.ec',
            },
            {
                'titulo': 'Encuentro Conecta Paz: Periodismo y Comunicación',
                'descripcion': 'Jornada académica binacional (Ecuador-Colombia) que reunirá a periodistas, comunicadores y académicos para reflexionar sobre el papel de la comunicación en la construcción de la paz. Se incluyen conferencias magistrales, paneles y talleres sobre periodismo en contextos de conflicto, ética informativa, innovación digital y narrativas que fomentan la cultura de paz. En el evento participarán invitados internacionales y locales.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 11, 27, 8, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Campus UTPL',
                'direccion': 'Campus UTPL (sede San Cayetano, Loja)',
                'precio': Decimal('0.00'),
                'contacto': 'Universidad Técnica Particular de Loja / Cátedra Colombia',
                'enlace': 'https://eventos.utpl.edu.ec',
            },
            
            # Más eventos de noviembre-diciembre 2025
            {
                'titulo': 'Obra de Teatro: Loja en Verso y Fuego',
                'descripcion': 'Montaje escénico que fusiona poesía lojana y danzas tradicionales con música andina en vivo.',
                'categoria': 'teatro',
                'fecha_inicio': datetime(2025, 11, 25, 19, 0, 0),
                'fecha_fin': datetime(2025, 11, 25, 21, 0, 0),
                'ubicacion': 'Teatro Nacional Benjamín Carrión',
                'direccion': 'Teatro Nacional Benjamín Carrión, Loja',
                'precio': Decimal('8.00'),
                'contacto': 'cultura@loja.gob.ec',
            },
            {
                'titulo': 'Exposición: Arte y Paisaje Saraguro',
                'descripcion': 'Obras pictóricas y textiles de artistas saraguros contemporáneos.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 11, 25, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 10, 17, 0, 0),
                'ubicacion': 'Museo de la Cultura Lojana',
                'direccion': 'Museo de la Cultura Lojana, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'museocultura@loja.gob.ec',
            },
            {
                'titulo': 'Concierto: Jazz Bajo las Estrellas',
                'descripcion': 'Noche de jazz en vivo con la banda "Andes Groove" y músicos invitados.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 11, 26, 20, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Plaza de San Sebastián',
                'direccion': 'Plaza de San Sebastián, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'eventos@loja.gob.ec',
            },
            {
                'titulo': 'Carrera Atlética: Loja Corre 10K',
                'descripcion': 'Competencia 5K y 10K abierta a todas las edades. Categorías juvenil y máster.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 11, 30, 7, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Parque Jipiro',
                'direccion': 'Salida desde Parque Jipiro, Loja',
                'precio': Decimal('10.00'),
                'contacto': 'deportes@loja.gob.ec',
            },
            {
                'titulo': 'Feria del Libro Independiente',
                'descripcion': 'Editoriales locales, charlas con escritores, talleres de escritura creativa.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 11, 28, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 1, 18, 0, 0),
                'ubicacion': 'Casa de la Cultura, Núcleo de Loja',
                'direccion': 'Casa de la Cultura, Núcleo de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'cultura.loja@cce.org.ec',
            },
            {
                'titulo': 'Encendido del Árbol Navideño',
                'descripcion': 'Show de villancicos, coro infantil, chocolate caliente y juegos pirotécnicos.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 1, 18, 30, 0),
                'fecha_fin': None,
                'ubicacion': 'Plaza Central de Loja',
                'direccion': 'Plaza Central de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'navidad@loja.gob.ec',
            },
            {
                'titulo': 'Festival Voces Jóvenes',
                'descripcion': 'Concurso de canto para talentos adolescentes. Jurado de músicos locales.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 11, 29, 17, 0, 0),
                'fecha_fin': datetime(2025, 11, 29, 21, 0, 0),
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Teatro Bolívar, Centro Histórico, Loja',
                'precio': Decimal('5.00'),
                'contacto': 'juventud@loja.gob.ec',
            },
            {
                'titulo': 'Taller: Yoga y Equilibrio Interior',
                'descripcion': 'Sesión guiada de yoga, meditación y respiración consciente.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 11, 27, 8, 0, 0),
                'fecha_fin': datetime(2025, 11, 27, 11, 0, 0),
                'ubicacion': 'Parque Universitario UTPL',
                'direccion': 'Jardines del Parque Universitario UTPL, Loja',
                'precio': Decimal('3.00'),
                'contacto': 'bienestar.utpl@edu.ec',
            },
            {
                'titulo': 'Festival de Bandas de Paz',
                'descripcion': 'Desfile con 12 bandas estudiantiles de Loja, Saraguro y Catamayo.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 2, 15, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Av. Universitaria',
                'direccion': 'Av. Universitaria, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'escuelas@loja.gob.ec',
            },
            {
                'titulo': 'Cine Foro: Documentales del Austro',
                'descripcion': 'Proyección de 3 cortos documentales sobre comunidades del sur ecuatoriano, con espacio de debate posterior.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 11, 28, 18, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Auditorio UTPL',
                'direccion': 'Auditorio UTPL, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'cineforo@utpl.edu.ec',
            },
            {
                'titulo': 'Feria Gastronómica: Sabores de Loja',
                'descripcion': 'Platos típicos de la región como repe lojano, tamales, arrope de mora, degustación de café y caña.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2025, 11, 29, 11, 0, 0),
                'fecha_fin': datetime(2025, 12, 1, 20, 0, 0),
                'ubicacion': 'Parque La Tebaida',
                'direccion': 'Parque La Tebaida, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'saboresloja@municipio.gob.ec',
            },
            {
                'titulo': 'Taller de Bordado Andino',
                'descripcion': 'Técnicas tradicionales de bordado aplicado a trajes típicos y accesorios.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 1, 14, 0, 0),
                'fecha_fin': datetime(2025, 12, 1, 17, 0, 0),
                'ubicacion': 'Centro Cultural Loja',
                'direccion': 'Centro Cultural Loja',
                'precio': Decimal('5.00'),
                'contacto': 'talleres@centrocultural.gob.ec',
            },
            {
                'titulo': 'Muestra de Danza: Raíces del Sur',
                'descripcion': 'Ballet folklórico de Loja con coreografías representando zonas rurales y urbanas.',
                'categoria': 'danza',
                'fecha_inicio': datetime(2025, 12, 3, 19, 30, 0),
                'fecha_fin': None,
                'ubicacion': 'Teatro Universitario UTPL',
                'direccion': 'Teatro Universitario UTPL, Loja',
                'precio': Decimal('6.00'),
                'contacto': 'danza.utpl@edu.ec',
            },
            {
                'titulo': 'Expo Fotográfica: Miradas del Azuay y Loja',
                'descripcion': 'Exposición conjunta de fotógrafos cuencanos y lojanos. Paisaje urbano, rural y retratos sociales.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 11, 25, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 5, 16, 0, 0),
                'ubicacion': 'Casa Tadeo Torres',
                'direccion': 'Casa Tadeo Torres, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'fotocultura@loja.gob.ec',
            },
            {
                'titulo': 'Misa y Procesión de la Inmaculada',
                'descripcion': 'Celebración litúrgica, procesión y cantos corales con acompañamiento de la Banda Municipal.',
                'categoria': 'religioso',
                'fecha_inicio': datetime(2025, 12, 8, 17, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Catedral de Loja',
                'direccion': 'Catedral de Loja, Centro Histórico',
                'precio': Decimal('0.00'),
                'contacto': 'parroquia.catedral@loja.gob.ec',
            },
            {
                'titulo': 'Presentación de Libro: Loja y sus Cuentos de Callejón',
                'descripcion': 'Conversatorio con el autor Pedro Llumiquinga, firma de libros y lectura de cuentos.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 4, 17, 30, 0),
                'fecha_fin': None,
                'ubicacion': 'Librería Palabra Libre',
                'direccion': 'Librería Palabra Libre, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'contacto@palabralibre.ec',
            },
            {
                'titulo': 'Jornada de Adopción de Mascotas',
                'descripcion': 'Adopción responsable, charlas sobre cuidado animal, vacunación gratuita.',
                'categoria': 'otro',
                'fecha_inicio': datetime(2025, 11, 30, 10, 0, 0),
                'fecha_fin': datetime(2025, 11, 30, 14, 0, 0),
                'ubicacion': 'Parque Infantil',
                'direccion': 'Parque Infantil, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'faunaurbana@loja.gob.ec',
            },
            {
                'titulo': 'Torneo Abierto de Ajedrez UTPL',
                'descripcion': 'Competencia para escolares, universitarios y profesionales. Rondas eliminatorias y premios por categoría.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 6, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 7, 17, 0, 0),
                'ubicacion': 'Campus UTPL',
                'direccion': 'Campus UTPL – Edificio de Innovación, Loja',
                'precio': Decimal('4.00'),
                'contacto': 'ajedrez@utpl.edu.ec',
            },
            
            # Más eventos variados de noviembre-diciembre 2025
            {
                'titulo': 'Concierto de Música Andina: Voces del Valle',
                'descripcion': 'Presentación de grupos locales de música andina con instrumentos tradicionales. Repertorio que incluye sanjuanitos, pasillos y música folclórica lojana.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 11, 28, 19, 30, 0),
                'fecha_fin': datetime(2025, 11, 28, 22, 0, 0),
                'ubicacion': 'Parque Central de Loja',
                'direccion': 'Parque Central, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'musica.loja@cultura.gob.ec',
            },
            {
                'titulo': 'Campeonato de Fútbol Interbarrios',
                'descripcion': 'Torneo de fútbol entre barrios de Loja. Semifinales y final del campeonato anual.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 1, 14, 0, 0),
                'fecha_fin': datetime(2025, 12, 1, 18, 0, 0),
                'ubicacion': 'Canchas Municipales de Loja',
                'direccion': 'Canchas Municipales, Av. 24 de Mayo, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'deportes.municipio@loja.gob.ec',
            },
            {
                'titulo': 'Exposición de Pintura: Rostros de Loja',
                'descripcion': 'Exposición colectiva de retratos de personajes lojanos realizados por artistas locales. Inauguración con vino de honor.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 2, 18, 0, 0),
                'fecha_fin': datetime(2025, 12, 15, 19, 0, 0),
                'ubicacion': 'Galería de Arte Municipal',
                'direccion': 'Calle Bernardo Valdivieso, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'galeria.arte@loja.gob.ec',
            },
            {
                'titulo': 'Festival de Comida Típica Lojana',
                'descripcion': 'Feria gastronómica con los mejores platos tradicionales: repe lojano, cecina, tamales, arrope de mora, quesadillas y más.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2025, 12, 3, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 3, 21, 0, 0),
                'ubicacion': 'Plaza de San Sebastián',
                'direccion': 'Plaza de San Sebastián, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'gastronomia@loja.gob.ec',
            },
            {
                'titulo': 'Seminario de Emprendimiento Juvenil',
                'descripcion': 'Seminario práctico sobre emprendimiento dirigido a jóvenes. Incluye talleres de plan de negocios, marketing digital y finanzas básicas.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 4, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 4, 17, 0, 0),
                'ubicacion': 'Centro de Convenciones UTPL',
                'direccion': 'Centro de Convenciones UTPL, Loja',
                'precio': Decimal('15.00'),
                'contacto': 'emprendimiento@utpl.edu.ec',
            },
            {
                'titulo': 'Procesión de la Virgen de Fátima',
                'descripcion': 'Procesión tradicional desde la iglesia de Fátima hasta la Catedral. Participación de fieles y comunidades religiosas.',
                'categoria': 'religioso',
                'fecha_inicio': datetime(2025, 12, 5, 16, 0, 0),
                'fecha_fin': None,
                'ubicacion': 'Iglesia de Fátima',
                'direccion': 'Iglesia de Fátima a Catedral de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'iglesia.fatima@loja.gob.ec',
            },
            {
                'titulo': 'Feria de Artesanías Navideñas',
                'descripcion': 'Feria con productos artesanales navideños, decoraciones, juguetes artesanales y regalos únicos elaborados por artesanos lojanos.',
                'categoria': 'feria',
                'fecha_inicio': datetime(2025, 12, 6, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 24, 20, 0, 0),
                'ubicacion': 'Parque Jipiro',
                'direccion': 'Parque Jipiro, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'artesanias@loja.gob.ec',
            },
            {
                'titulo': 'Obra de Teatro: La Leyenda de la Llorona',
                'descripcion': 'Adaptación teatral de la leyenda popular lojana. Dirección del grupo teatral local "Tablas del Sur".',
                'categoria': 'teatro',
                'fecha_inicio': datetime(2025, 12, 7, 20, 0, 0),
                'fecha_fin': datetime(2025, 12, 7, 22, 0, 0),
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Teatro Bolívar, Calle Rocafuerte, Centro Histórico, Loja',
                'precio': Decimal('8.00'),
                'contacto': 'teatro.bolivar@loja.gob.ec',
            },
            {
                'titulo': 'Gala de Danza Folclórica: Tradiciones Lojanas',
                'descripcion': 'Espectáculo de danza folclórica con grupos locales. Coreografías representando las diferentes zonas de Loja.',
                'categoria': 'danza',
                'fecha_inicio': datetime(2025, 12, 8, 19, 0, 0),
                'fecha_fin': datetime(2025, 12, 8, 21, 30, 0),
                'ubicacion': 'Teatro Universitario UTPL',
                'direccion': 'Teatro Universitario UTPL, Loja',
                'precio': Decimal('7.00'),
                'contacto': 'danza.utpl@edu.ec',
            },
            {
                'titulo': 'Conferencia: Historia de Loja Colonial',
                'descripcion': 'Charla magistral sobre la historia colonial de Loja a cargo del historiador Dr. Carlos Espinoza. Incluye proyección de imágenes históricas.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 9, 15, 0, 0),
                'fecha_fin': datetime(2025, 12, 9, 17, 30, 0),
                'ubicacion': 'Museo de la Cultura Lojana',
                'direccion': 'Museo de la Cultura Lojana, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'museo.cultura@loja.gob.ec',
            },
            {
                'titulo': 'Concierto de Navidad: Coros de Loja',
                'descripcion': 'Concierto navideño con la participación de coros de diferentes instituciones de Loja. Repertorio de villancicos tradicionales y modernos.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 12, 10, 18, 0, 0),
                'fecha_fin': datetime(2025, 12, 10, 20, 30, 0),
                'ubicacion': 'Catedral de Loja',
                'direccion': 'Catedral de Loja, Centro Histórico',
                'precio': Decimal('0.00'),
                'contacto': 'musica.catedral@loja.gob.ec',
            },
            {
                'titulo': 'Torneo de Voleibol Femenino',
                'descripcion': 'Competencia de voleibol femenino entre equipos de Loja y ciudades vecinas. Categorías juvenil y senior.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 11, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 11, 17, 0, 0),
                'ubicacion': 'Coliseo de Loja',
                'direccion': 'Coliseo de Loja, Av. 8 de Diciembre',
                'precio': Decimal('3.00'),
                'contacto': 'voley.loja@deportes.gob.ec',
            },
            {
                'titulo': 'Taller de Pintura para Niños',
                'descripcion': 'Taller creativo de pintura dirigido a niños de 6 a 12 años. Trabajaremos con acuarelas y técnicas básicas de expresión artística.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 12, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 12, 12, 0, 0),
                'ubicacion': 'Centro Cultural Loja',
                'direccion': 'Centro Cultural Loja, Loja',
                'precio': Decimal('5.00'),
                'contacto': 'talleres.niños@cultura.gob.ec',
            },
            {
                'titulo': 'Festival de Música Rock Alternativo',
                'descripcion': 'Festival de rock alternativo con bandas locales y nacionales. Ambiente juvenil y música en vivo durante toda la noche.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 12, 13, 18, 0, 0),
                'fecha_fin': datetime(2025, 12, 13, 23, 0, 0),
                'ubicacion': 'Parque La Tebaida',
                'direccion': 'Parque La Tebaida, Loja',
                'precio': Decimal('12.00'),
                'contacto': 'rock.loja@eventos.com',
            },
            {
                'titulo': 'Exposición de Cerámica Indígena',
                'descripcion': 'Exposición de cerámica tradicional de comunidades indígenas de la provincia de Loja. Piezas históricas y contemporáneas.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 14, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 20, 18, 0, 0),
                'ubicacion': 'Museo de Arqueología',
                'direccion': 'Museo de Arqueología, Loja',
                'precio': Decimal('2.00'),
                'contacto': 'arqueologia@loja.gob.ec',
            },
            {
                'titulo': 'Ciclo de Cine Latinoamericano',
                'descripcion': 'Proyección de películas latinoamericanas contemporáneas. Incluye cortometrajes ecuatorianos y charlas con directores.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 15, 19, 0, 0),
                'fecha_fin': datetime(2025, 12, 15, 22, 0, 0),
                'ubicacion': 'Auditorio UTPL',
                'direccion': 'Auditorio UTPL, Campus Universitario, Loja',
                'precio': Decimal('3.00'),
                'contacto': 'cine.utpl@edu.ec',
            },
            {
                'titulo': 'Torneo de Básquet Intercolegial',
                'descripcion': 'Competencia de básquet entre colegios de Loja. Categorías masculina y femenina. Final del torneo anual.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 16, 8, 0, 0),
                'fecha_fin': datetime(2025, 12, 16, 16, 0, 0),
                'ubicacion': 'Coliseo Ciudad de Loja',
                'direccion': 'Coliseo Ciudad de Loja, Av. Universitaria',
                'precio': Decimal('2.00'),
                'contacto': 'basquet.loja@deportes.gob.ec',
            },
            {
                'titulo': 'Festival de Chocolate y Café',
                'descripcion': 'Degustación de chocolates artesanales y café de altura de Loja. Charlas sobre proceso de producción y catas guiadas.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2025, 12, 17, 11, 0, 0),
                'fecha_fin': datetime(2025, 12, 17, 19, 0, 0),
                'ubicacion': 'Plaza de San Francisco',
                'direccion': 'Plaza de San Francisco, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'cafe.chocolate@loja.gob.ec',
            },
            {
                'titulo': 'Conferencia sobre Turismo Sostenible',
                'descripcion': 'Jornada académica sobre turismo sostenible y ecoturismo en la provincia de Loja. Experiencias y proyectos locales.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 18, 14, 0, 0),
                'fecha_fin': datetime(2025, 12, 18, 18, 0, 0),
                'ubicacion': 'Universidad Nacional de Loja',
                'direccion': 'Auditorio UNL, Campus Universitario, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'turismo@unl.edu.ec',
            },
            {
                'titulo': 'Novena de Navidad',
                'descripcion': 'Celebración tradicional de la novena de Navidad con cánticos, rezos y reflexiones navideñas. Todos los días hasta Navidad.',
                'categoria': 'religioso',
                'fecha_inicio': datetime(2025, 12, 16, 18, 0, 0),
                'fecha_fin': datetime(2025, 12, 24, 19, 0, 0),
                'ubicacion': 'Parroquia de San Sebastián',
                'direccion': 'Parroquia de San Sebastián, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'parroquia.sansebastian@loja.gob.ec',
            },
            {
                'titulo': 'Feria de Emprendedores Navideños',
                'descripcion': 'Feria con productos y servicios de emprendedores locales. Ideal para hacer compras navideñas y apoyar el comercio local.',
                'categoria': 'feria',
                'fecha_inicio': datetime(2025, 12, 19, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 23, 21, 0, 0),
                'ubicacion': 'Parque Central de Loja',
                'direccion': 'Parque Central, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'emprendedores@loja.gob.ec',
            },
            {
                'titulo': 'Obra de Teatro Infantil: El Mago de Oz',
                'descripcion': 'Adaptación teatral del clásico para toda la familia. Presentación del grupo teatral infantil de Loja.',
                'categoria': 'teatro',
                'fecha_inicio': datetime(2025, 12, 20, 16, 0, 0),
                'fecha_fin': datetime(2025, 12, 20, 17, 30, 0),
                'ubicacion': 'Teatro Nacional Benjamín Carrión',
                'direccion': 'Teatro Nacional Benjamín Carrión, Loja',
                'precio': Decimal('5.00'),
                'contacto': 'teatro.nacional@loja.gob.ec',
            },
            {
                'titulo': 'Presentación de Ballet: El Cascanueces',
                'descripcion': 'Espectáculo de ballet clásico con la presentación de El Cascanueces. Compañía de danza local con invitados especiales.',
                'categoria': 'danza',
                'fecha_inicio': datetime(2025, 12, 21, 19, 30, 0),
                'fecha_fin': datetime(2025, 12, 21, 21, 30, 0),
                'ubicacion': 'Teatro Bolívar',
                'direccion': 'Teatro Bolívar, Centro Histórico, Loja',
                'precio': Decimal('12.00'),
                'contacto': 'ballet.loja@cultura.gob.ec',
            },
            {
                'titulo': 'Concierto de Guitarra Clásica',
                'descripcion': 'Recital de guitarra clásica a cargo del maestro lojano Juan Carlos Espinoza. Repertorio de música latinoamericana y española.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 12, 22, 19, 0, 0),
                'fecha_fin': datetime(2025, 12, 22, 21, 0, 0),
                'ubicacion': 'Casa de la Cultura Loja',
                'direccion': 'Casa de la Cultura, Núcleo de Loja',
                'precio': Decimal('6.00'),
                'contacto': 'guitarra.clasica@cultura.gob.ec',
            },
            {
                'titulo': 'Maratón de Lectura Infantil',
                'descripcion': 'Actividad de fomento a la lectura para niños. Lectura de cuentos, actividades lúdicas y entrega de libros donados.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2025, 12, 23, 10, 0, 0),
                'fecha_fin': datetime(2025, 12, 23, 13, 0, 0),
                'ubicacion': 'Biblioteca Municipal',
                'direccion': 'Biblioteca Municipal de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'biblioteca@loja.gob.ec',
            },
            {
                'titulo': 'Festival de Luces Navideñas',
                'descripcion': 'Encendido de luces navideñas en el centro histórico. Música en vivo, comida callejera y ambiente festivo familiar.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 24, 18, 30, 0),
                'fecha_fin': datetime(2025, 12, 24, 22, 0, 0),
                'ubicacion': 'Centro Histórico de Loja',
                'direccion': 'Centro Histórico de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'navidad@loja.gob.ec',
            },
            {
                'titulo': 'Misa de Gallo',
                'descripcion': 'Misa tradicional de Navidad a las 12 de la medianoche. Celebración litúrgica con coros y música sacra.',
                'categoria': 'religioso',
                'fecha_inicio': datetime(2025, 12, 25, 0, 0, 0),
                'fecha_fin': datetime(2025, 12, 25, 1, 30, 0),
                'ubicacion': 'Catedral de Loja',
                'direccion': 'Catedral de Loja, Centro Histórico',
                'precio': Decimal('0.00'),
                'contacto': 'catedral.loja@iglesia.ec',
            },
            {
                'titulo': 'Festival Gastronómico: Sabores de Navidad',
                'descripcion': 'Feria con platos típicos navideños lojanos: tamales, arroz con leche, buñuelos, pristiños y bebidas tradicionales.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2025, 12, 24, 14, 0, 0),
                'fecha_fin': datetime(2025, 12, 24, 22, 0, 0),
                'ubicacion': 'Plaza de la Independencia',
                'direccion': 'Plaza de la Independencia, Centro Histórico, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'gastronomia.navidad@loja.gob.ec',
            },
            {
                'titulo': 'Torneo de Ajedrez Rápido',
                'descripcion': 'Competencia de ajedrez con formato rápido (blitz). Categorías abierta, juvenil y senior. Premios para los ganadores.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 26, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 26, 17, 0, 0),
                'ubicacion': 'Club de Ajedrez Loja',
                'direccion': 'Club de Ajedrez Loja, Centro Histórico',
                'precio': Decimal('8.00'),
                'contacto': 'ajedrez.loja@deportes.gob.ec',
            },
            {
                'titulo': 'Taller de Cocina Navideña',
                'descripcion': 'Aprende a preparar los mejores platos navideños lojanos. Incluye recetas de tamales, buñuelos y pristiños tradicionales.',
                'categoria': 'gastronomia',
                'fecha_inicio': datetime(2025, 12, 27, 15, 0, 0),
                'fecha_fin': datetime(2025, 12, 27, 18, 0, 0),
                'ubicacion': 'Escuela de Gastronomía UTPL',
                'direccion': 'Escuela de Gastronomía UTPL, Campus Universitario',
                'precio': Decimal('20.00'),
                'contacto': 'gastronomia@utpl.edu.ec',
            },
            {
                'titulo': 'Noche de Boleros y Románticos',
                'descripcion': 'Concierto de música romántica con boleros, baladas y canciones de amor. Ambiente íntimo para parejas.',
                'categoria': 'musica',
                'fecha_inicio': datetime(2025, 12, 28, 20, 0, 0),
                'fecha_fin': datetime(2025, 12, 28, 23, 0, 0),
                'ubicacion': 'Restaurante La Casona',
                'direccion': 'Restaurante La Casona, Centro Histórico, Loja',
                'precio': Decimal('15.00'),
                'contacto': 'lacasona.loja@restaurante.com',
            },
            {
                'titulo': 'Exposición Fotográfica: Loja en Navidad',
                'descripcion': 'Exposición de fotografías que capturan la esencia de Loja durante la temporada navideña. Trabajos de fotógrafos locales.',
                'categoria': 'cultural',
                'fecha_inicio': datetime(2025, 12, 29, 10, 0, 0),
                'fecha_fin': datetime(2026, 1, 10, 18, 0, 0),
                'ubicacion': 'Casa de la Cultura Loja',
                'direccion': 'Casa de la Cultura, Núcleo de Loja',
                'precio': Decimal('0.00'),
                'contacto': 'fotografia@cultura.gob.ec',
            },
            {
                'titulo': 'Torneo de Tenis de Mesa',
                'descripcion': 'Competencia de tenis de mesa abierta a todas las edades. Categorías individual y dobles. Inscripciones abiertas.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2025, 12, 30, 9, 0, 0),
                'fecha_fin': datetime(2025, 12, 30, 17, 0, 0),
                'ubicacion': 'Polideportivo de Loja',
                'direccion': 'Polideportivo de Loja, Av. 8 de Diciembre',
                'precio': Decimal('5.00'),
                'contacto': 'tenisdemesa@deportes.gob.ec',
            },
            {
                'titulo': 'Celebración de Año Nuevo: Fiesta en la Plaza',
                'descripcion': 'Celebración masiva de fin de año en la plaza central. Música en vivo, fuegos artificiales y ambiente festivo para recibir el 2026.',
                'categoria': 'otro',
                'fecha_inicio': datetime(2025, 12, 31, 21, 0, 0),
                'fecha_fin': datetime(2026, 1, 1, 1, 0, 0),
                'ubicacion': 'Plaza Central de Loja',
                'direccion': 'Plaza Central de Loja, Centro Histórico',
                'precio': Decimal('0.00'),
                'contacto': 'eventos@loja.gob.ec',
            },
            {
                'titulo': 'Maratón de Año Nuevo: Corre hacia el 2026',
                'descripcion': 'Maratón temática de Año Nuevo con recorrido por las principales calles de Loja. Categorías 5K, 10K y 21K. Entrega de medallas.',
                'categoria': 'deporte',
                'fecha_inicio': datetime(2026, 1, 1, 6, 0, 0),
                'fecha_fin': datetime(2026, 1, 1, 11, 0, 0),
                'ubicacion': 'Parque Jipiro',
                'direccion': 'Salida desde Parque Jipiro, Loja',
                'precio': Decimal('12.00'),
                'contacto': 'maraton.anionuevo@deportes.gob.ec',
            },
            {
                'titulo': 'Obra de Teatro: La Casa de Bernarda Alba',
                'descripcion': 'Adaptación de la obra clásica de García Lorca. Dirección del grupo teatral universitario de la UNL.',
                'categoria': 'teatro',
                'fecha_inicio': datetime(2026, 1, 3, 19, 30, 0),
                'fecha_fin': datetime(2026, 1, 3, 22, 0, 0),
                'ubicacion': 'Teatro Universitario UNL',
                'direccion': 'Teatro Universitario UNL, Campus Universitario, Loja',
                'precio': Decimal('6.00'),
                'contacto': 'teatro.unl@unl.edu.ec',
            },
            {
                'titulo': 'Conferencia sobre Biodiversidad de Loja',
                'descripcion': 'Charla sobre la rica biodiversidad de la provincia de Loja. Proyección de documentales sobre flora y fauna local.',
                'categoria': 'educativo',
                'fecha_inicio': datetime(2026, 1, 4, 15, 0, 0),
                'fecha_fin': datetime(2026, 1, 4, 17, 30, 0),
                'ubicacion': 'Auditorio UTPL',
                'direccion': 'Auditorio UTPL, Campus Universitario, Loja',
                'precio': Decimal('0.00'),
                'contacto': 'biodiversidad@utpl.edu.ec',
            },
        ]
        
        # Convertir fechas a timezone-aware si no lo son
        for evento_data in eventos_data:
            if not timezone.is_aware(evento_data['fecha_inicio']):
                evento_data['fecha_inicio'] = timezone.make_aware(evento_data['fecha_inicio'])
            if evento_data.get('fecha_fin') and not timezone.is_aware(evento_data['fecha_fin']):
                evento_data['fecha_fin'] = timezone.make_aware(evento_data['fecha_fin'])
        
        # Crear eventos
        eventos_creados = 0
        for evento_data in eventos_data:
            evento, created = Evento.objects.get_or_create(
                titulo=evento_data['titulo'],
                fecha_inicio=evento_data['fecha_inicio'],
                defaults=evento_data
            )
            if created:
                eventos_creados += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✓ Creado: {evento.titulo}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'⊘ Ya existe: {evento.titulo}')
                )
        
        self.stdout.write(
            self.style.SUCCESS(
                f'\n¡Listo! Se crearon {eventos_creados} eventos nuevos. '
                f'Total de eventos en la base de datos: {Evento.objects.count()}'
            )
        )

